#!/bin/bash

apt-get update
apt-get install npm
apt-get install nodejs
apt-get install git
npm install bower -g
ln -s /usr/bin/nodejs /usr/bin/node
apt-get install libapache2-mod-python libapache2-mod-python-doc apache2
cd /var/www/html/
git clone git://github.com/densitydesign/raw.git
cd raw/
bower install
