#!/bin/sh
set -e
#
# This script is only meant to work on Debian (Ubuntu)
# 
# This script is meant for quick & easy install via:
#   'curl -sSL https://<url>.domain.com/ | sh'
# or:
#   'wget -qO- https://<url>.domain.com/ | sh'
#

url=''


command_exists() {
	command -v "$@" > /dev/null 2>&1
}

case "$(uname -m)" in
	*64)
		;;
	*)
		echo >&2 'Error: you are not using a 64bit platform.'
		exit 1
		;;
esac


user="$(id -un 2>/dev/null || true)"

sh_c='sh -c'
if [ "$user" != 'root' ]; then
        if command_exists sudo; then
                sh_c='sudo -E sh -c'
        elif command_exists su; then
                sh_c='su -c'
        else
                echo >&2 'Error: this installer needs the ability to run commands as root.'
                echo >&2 'We are unable to find either "sudo" or "su" available to make this happen.'
                exit 1
        fi
fi

curl=''
if command_exists curl; then
        curl='curl -sSL'
elif command_exists wget; then
        curl='wget -qO-'
fi

		(
			set -x
			$sh_c 'sleep 3; apt-get update'
			$sh_c 'sleep 3; apt-get install npm nodejs git libapache2-mod-python libapache2-mod-python-doc apache2'
			$sh_c 'npm install bower -g'
			$sh_c 'sleep 3; ln -s /usr/bin/nodej'
			$sh_c 'cd /var/www/html/; git clone git://github.com/densitydesign/raw.git; cd raw; bower install'
		)
	



EOF
exit 1
